trigger:
  branches:
    include:
      - main
      - development

pool:
  vmImage: 'ubuntu-latest'

stages:
# Stage 1: Build
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: Build
    displayName: "Build and Test"
    steps:
    - script: |
        npm install
      displayName: "Install dependencies"
    - script: |
        npx eslint .
      displayName: "Run ESLint (Static Code Analysis)"
    - script: |
        npm test
      displayName: "Run Unit Tests"

# Stage 2: Performance Testing
- stage: PerformanceTesting
  displayName: "Performance Testing"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: RunPerformanceTests
    displayName: "Run Performance Tests with Benchmark.js"
    steps:
    - script: |
        node performance-benchmark.js
      displayName: "Execute Performance Tests"

# Stage 3: Security Testing
- stage: SecurityTesting
  displayName: "Security Testing"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: RunNpmAudit
    displayName: "Run npm audit"
    steps:
    - script: |
        npm audit --production
      displayName: "Execute npm audit"

# Stage 4: Deploy to Test
- stage: DeployToTest
  displayName: "Deploy to Test Environment"
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development')) # Triggered only by development branch
  jobs:
  - deployment: DeployToTest
    displayName: "Deploy to Test Environment"
    environment: Test # Links to the Test environment in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying to Test Environment"
            displayName: "Deploy Application"

# Stage 5: Deploy to Production
- stage: DeployToProduction
  displayName: "Deploy to Production Environment"
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main')) # Triggered only by main branch
  jobs:
  - deployment: DeployToProduction
    displayName: "Deploy to Production Environment"
    environment: Production # Links to the Production environment in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying to Production Environment"
            displayName: "Deploy Application"
