trigger:
  branches:
    include:
      - main
      - development

pool:
  vmImage: 'ubuntu-latest'

stages:
# Stage 1: Build
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: Build
    displayName: "Build and Test"
    steps:
    - script: |
        npm install --include=dev
        npm list --depth=0
      displayName: "Install dependencies and list installed modules"
    - script: |
        npx eslint .
      displayName: "Run ESLint (Static Code Analysis)"
    - script: |
        npm test
      displayName: "Run Unit Tests"

# Stage 2: Performance Testing
- stage: PerformanceTesting
  displayName: "Performance Testing"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: RunPerformanceTests
    displayName: "Run Performance Tests with Benchmark.js"
    steps:
    - script: |
        ls -la
      displayName: "Check workspace before npm install"
    - script: |
        rm -rf node_modules package-lock.json
        npm install --include=dev
        npm list --depth=0
      displayName: "Clean and reinstall dependencies"
    - script: |
        ls -la node_modules
        ls -la node_modules/benchmark
      displayName: "Verify dependencies installation"
    - script: |
        node performance-benchmark.js
      displayName: "Execute Performance Tests"

# Stage 3: Security Testing
- stage: SecurityTesting
  displayName: "Security Testing"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: RunNpmAudit
    displayName: "Run npm audit"
    steps:
    - script: |
        npm audit --production
      displayName: "Execute npm audit"

# Stage 4: Deploy to Test
- stage: DeployToTest
  displayName: "Deploy to Test Environment"
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development')) # Triggered only by development branch
  jobs:
  - deployment: DeployToTest
    displayName: "Deploy to Test Environment"
    environment: Test # Links to the Test environment in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying to Test Environment"
            displayName: "Deploy Application"

# Stage 5: Deploy to Production
- stage: DeployToProduction
  displayName: "Deploy to Production Environment"
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main')) # Triggered only by main branch
  jobs:
  - deployment: DeployToProduction
    displayName: "Deploy to Production Environment"
    environment: Production 
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying to Production Environment"
            displayName: "Deploy Application"

# Stage 6: UAT Testing with Selenium
- stage: UATTesting
  displayName: "UAT Testing with Selenium"
  dependsOn: DeployToTest
  condition: succeeded()
  jobs:
  - job: RunUATTests
    displayName: "Run Selenium UAT Tests"
    steps:
    - script: |
        ls -la
      displayName: "Verify Workspace Files"

    - script: |
        npm install selenium-webdriver chromedriver --save-dev
        npm list --depth=0
      displayName: "Install Selenium and WebDriver Dependencies"

    - script: |
        node selenium-tests.js
      displayName: "Execute Selenium Tests"
