trigger:
  branches:
    include:
      - development

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  # Clean the workspace
  - script: |
      git clean -fdx
      git reset --hard
    displayName: "Clean workspace"

  # Install Dependencies
  - script: npm install
    displayName: 'Install dependencies'

  # Debug Environment
  - script: |
      echo "Node Version:"
      node -v
      echo "NPM Version:"
      npm -v
      echo "ESLint Config File:"
      ls -la eslint.config.js
      echo "ESLint Config Contents:"
      cat eslint.config.js
    displayName: "Debug Environment and ESLint Config"

  # Run ESLint
  - script: npx eslint .
    displayName: 'Run ESLint (Static Code Analysis)'
