trigger:
  branches:
    include:
      - development

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  # Install Dependencies
  - script: npm install
    displayName: 'Install dependencies'

  # Debug ESLint Config
  - script: |
      echo "Checking ESLint Config"
      ls -la eslint.config.js
      cat eslint.config.js
    displayName: "Debug ESLint Config"

  # Run ESLint
  - script: npx eslint .
    displayName: 'Run ESLint (Static Code Analysis)'
